apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgresql-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: postgresql-pv   # 🔹 Explicitly bind to PV
  storageClassName: gp2       # 🔹 Ensure it matches PV storage class

